name: Auto Merge PR

on:
  pull_request_review:
    types: [submitted]

permissions:
  contents: write

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    if: github.event.review.state == 'approved'
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Auto merge pull request
      uses: actions/github-script@v4
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        script: |
          const pr_number = context.payload.pull_request.number;
          const owner = context.repo.owner;
          const repo = context.repo.repo;

          console.log(`PR Number: ${pr_number}`);
          console.log(`Owner: ${owner}`);
          console.log(`Repo: ${repo}`);

          // Check if the PR is mergeable
          const { data: pullRequest } = await github.pulls.get({
            owner: owner,
            repo: repo,
            pull_number: pr_number
          });

          console.log(`Mergeable: ${pullRequest.mergeable}`);

          if (pullRequest.mergeable) {
            // Merge the PR
            await github.pulls.merge({
              owner: owner,
              repo: repo,
              pull_number: pr_number,
              merge_method: 'merge' // or 'squash' or 'rebase'
            });
            console.log(`Pull request #${pr_number} merged successfully.`);
          } else {
            console.log(`Pull request #${pr_number} is not mergeable.`);
          }
