name: Restrict Issue Editing

on:
  issues:
    types: [edited, closed]

jobs:
  restrict_editing:
    runs-on: ubuntu-latest
    steps:
    - name: Check and Revert Changes
      uses: actions/github-script@v4
      with:
        script: |
          const issue_number = context.issue.number;
          const owner = context.repo.owner;
          const repo = context.repo.repo;

          // Issueの状態を取得
          const issue = await github.issues.get({
            owner: owner,
            repo: repo,
            issue_number: issue_number
          });

          // IssueがDoneになった場合の処理
          if (issue.data.state === 'closed' || issue.data.labels.some(label => label.name === 'Done')) {
            // タイトルや説明の変更を元に戻す（ここでは仮に設定）
            const original_title = "Original Issue Title";
            const original_body = "Original Issue Description";

            // 現在のタイトルと説明を取得
            const current_title = issue.data.title;
            const current_body = issue.data.body;

            // タイトルが変更された場合、元に戻す
            if (current_title !== original_title) {
              await github.issues.update({
                owner: owner,
                repo: repo,
                issue_number: issue_number,
                title: original_title
              });
            }

            // 説明が変更された場合、元に戻す
            if (current_body !== original_body) {
              await github.issues.update({
                owner: owner,
                repo: repo,
                issue_number: issue_number,
                body: original_body
              });
            }
          }
