name: Lock Closed Issues

on:
  issues:
    types: [closed]

jobs:
  lock_issue:
    runs-on: ubuntu-latest
    steps:
    - name: Lock closed issue
      uses: actions/github-script@v4
      with:
        script: |
          const issue_number = context.issue.number;
          const owner = context.repo.owner;
          const repo = context.repo.repo;

          console.log('Locking issue:', issue_number);
          // Lock the issue
          await github.issues.lock({
            owner: owner,
            repo: repo,
            issue_number: issue_number
          });
          console.log('Issue locked:', issue_number);
