name: Revert Issue Changes

on:
  issues:
    types: [edited]

jobs:
  revert_changes:
    runs-on: ubuntu-latest
    steps:
    - name: Revert Issue Changes
      uses: actions/github-script@v4
      with:
        script: |
          const issue_number = context.issue.number;
          const owner = context.repo.owner;
          const repo = context.repo.repo;

          // Issueの状態を取得
          const issue = await github.issues.get({
            owner: owner,
            repo: repo,
            issue_number: issue_number
          });

          // Issueのコメントを取得
          const comments = await github.issues.listComments({
            owner: owner,
            repo: repo,
            issue_number: issue_number
          });

          // 保存された状態を含むコメントを見つける
          const savedStateComment = comments.data.find(comment => comment.body.startsWith('<!-- saved-state -->'));

          if (savedStateComment) {
            // 保存された状態を解析
            const savedState = savedStateComment.body.match(/Title: (.*)\nBody: ([\s\S]*)/);

            if (savedState) {
              const savedTitle = savedState[1];
              const savedBody = savedState[2];

              // 現在のタイトルと説明を取得
              const currentTitle = issue.data.title;
              const currentBody = issue.data.body;

              // タイトルが変更された場合、元に戻す
              if (currentTitle !== savedTitle) {
                await github.issues.update({
                  owner: owner,
                  repo: repo,
                  issue_number: issue_number,
                  title: savedTitle
                });
              }

              // 説明が変更された場合、元に戻す
              if (currentBody !== savedBody) {
                await github.issues.update({
                  owner: owner,
                  repo: repo,
                  issue_number: issue_number,
                  body: savedBody
                });
              }
            } else {
              console.log('Saved state format is incorrect.');
            }
          } else {
            console.log('No saved state comment found.');
          }
